;;; quarto-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from quarto-mode.el

 (autoload 'poly-quarto-mode "quarto-mode")
 (autoload 'poly-quarto-mode "quarto-mode")
(add-to-list 'auto-mode-alist '("\\.qmd\\'" . poly-quarto-mode))
(register-definition-prefixes "quarto-mode" '("quarto-"))

;;; End of scraped data

(provide 'quarto-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; quarto-mode-autoloads.el ends here
