;;; Automatically generated by ‘recentf’ on Fri Nov 24 12:50:31 2023.

(setq recentf-list
      '(
        "~/MyProjects/Notes/README.md"
        "~/MyProjects/Notes/Papers/reversibleJump.qmd"
        "~/.config/emacs/var/emacs-session/10c2d322d58bd8d13d170074955851821900000025280106"
        "~/.config/emacs/config.org"
        "~/.config/emacs/latextest.tex"
        "~/.config/emacs/elpaca/builds/scala-mode/ob-scala.el"
        "~/.config/emacs/ob-scala.el"
        "/usr/share/emacs/29.1/lisp/loaddefs.el.gz"
        "~/orgfiles/readinglist.org"
        "~/.config/waybar/config.json"
        "~/.config/waybar/style.css"
        "~/.config/hypr/hyprland.conf"
        "~/.config/emacs/var/emacs-session/108dbf2b37a6ff5bdf170068898857721200000332470079"
        "~/.config/emacs/var/emacs-session/1042fae168247cd1ef170068877838120300000279640080"
        "~/.config/emacs/var/emacs-session/10fc163e172adfee12170066428017953600000024780087"
        "~/MyProjects/mcmcinscala/src/main/scala/Main.scala"
        "~/MyProjects/Notes/HandbookofMCMC/MCMCnotes.qmd"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
